---
- name: check csv loop example
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name:  import csv
      csv_to_facts:
        src: '{{ playbook_dir }}/Fabric01/switches.csv'
    - name: "read csv" for loop
      raw: echo {{ item }}
      loop: '{{ spreadsheet }}'
